### ISSUE TITLE
Add options to run at startup, minimize to system tray and save settings

### ISSUE THREAD

**Issue by mdecroos** [mkapulica/NFC-UID-Keyboard-Emulator#1]
it would be nice to start the keyboard-wedge directly into a tray icon with the selected options ... possible to add this ?

**Comment by mkapulica** [comment]
@mdecroos, settings need to be saved to an external file or to the registry. What would you prefer?
If you want settings to be easily transferred between PCs it would be best to put them in a separate file in the same directory as the executable file. Otherwise I would rather put them inside the Windows user's `AppData\Local` directory so they're hidden away.

**Comment by Wortho27** [comment]
AppData\Local sounds pretty good, and easy.
How are we going for a release for the startup configuration feature?

**Comment by mkapulica** [comment]
> AppData\Local sounds pretty good, and easy. How are we going for a release for the startup configuration feature?

I have prepared everything in a new feature branch months ago, but I was waiting for a reply so I didn't finish it... Until today.
I've opted out for an external JSON file in the same directory since it will make it easier to deploy on multiple PCs with the same settings.

**Comment by mkapulica** [comment]
All the requested features have been added and you can download the new version under the [latest release](https://github.com/mkapulica/NFC-UID-Keyboard-Emulator/releases/tag/v1.3.0).

You can download the executable, or build it yourself. The executable has a drastic increase in size (1.2 MB now) since every dependency is embedded and we now need a way to handle JSON files for reading and writing settings.
